In [0]:
!pip install tensorflow-gpu==2.0.0rc numpy tqdm matplotlib --no-cache-dir


     |████████████████████████████████| 380.5MB 1.3MB/s 
     |████████████████████████████████| 501kB 24.9MB/s 
     |████████████████████████████████| 4.3MB 28.9MB/s 


# New Section

In [0]:
pip install keras

In [10]:
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import precision_score , recall_score
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 


import keras
import tensorflow as tf
import numpy as np
import pandas as pd



# Get the input data from the data set.
def getInputData(dataset):
  inputDataset = []
  for i in range(len(dataset)):
    inputDataset.append(dataset[i][0:4])
  return inputDataset
   
# Get the desired data from the dataset 
def getDesiredData(dataset):
  desiredDataset = []
  classifier = []
  for i in range(len(dataset)):
    if dataset[i][4] == "Iris-setosa":
      desiredDataset.append([1, 0, 0])
      classifier.append(0)
    if dataset[i][4] == "Iris-versicolor":
      desiredDataset.append([0, 1, 0])
      classifier.append(1)
    if dataset[i][4] == "Iris-virginica":
      desiredDataset.append([0, 0, 1])
      classifier.append(2)
  return desiredDataset,classifier

def model(training_input_data,training_data_desired_label,testing_input_data,testing_data_desired_label,training_classifier, testing_classifier):
  # Build the model
  model = Sequential()
  model.add(Dense(3,input_shape=(4,), activation='sigmoid'))

  model.compile(Adam(lr=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

  # Train the model
  model.fit(np.asarray(training_input_data), np.asarray(training_data_desired_label), verbose=0, batch_size=5, epochs=10000)

  #evaluate the data set.
  predictTesting = model.predict_classes(np.asarray(testing_input_data))
  print("Testing dataset confusion matrix: \n", confusion_matrix(testing_classifier, predictTesting))
  print('Testing dataset Accuracy Score: \n', accuracy_score(testing_classifier, predictTesting))
  print('Testing dataset Report : \n',classification_report(testing_classifier, predictTesting))

  predictTraining = model.predict_classes(np.asarray(training_input_data))
  print("Testing dataset confusion matrix: \n", confusion_matrix(training_classifier, predictTraining))
  print('Testing dataset Accuracy Score:\n', accuracy_score(training_classifier, predictTraining))
  print('Testing dataset Report :\n ', classification_report(training_classifier, predictTraining))
  
  
def main():
  # Read into the training data and testing data.
  new_names = ['sepal_length','sepal_width','petal_length','petal_width','iris_category']
  traingingDataset = pd.read_csv('iris_train.txt', delimiter=",", header=None)
  traingingDataset = traingingDataset.as_matrix()
  testingDataset = pd.read_csv('iris_test.txt', delimiter=",", header=None)
  testingDataset=testingDataset.as_matrix()
  
  # Sparate the training test set and desired label.
  training_input_data = getInputData(traingingDataset)
  training_data_desired_label, training_classifier = getDesiredData(traingingDataset)
  testing_input_data = getInputData(testingDataset)
  testing_data_desired_label, testing_classifier = getDesiredData(testingDataset)
  
  # Create, train and evaluate the model.
  model(training_input_data,training_data_desired_label,testing_input_data,testing_data_desired_label,training_classifier,testing_classifier)
  

main()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:68: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:70: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


Testing dataset confusion matrix: 
 [[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
Testing dataset Accuracy Score: 
 0.9333333333333333
Testing dataset Report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      1.00      0.91        10
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30

Testing dataset confusion matrix: 
 [[40  0  0]
 [ 0 38  2]
 [ 0  0 40]]
Testing dataset Accuracy Score:
 0.9833333333333333
Testing dataset Report :
                precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      0.95      0.97        40
           2       0.95      1.00      0.98        40

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.9

In [4]:
pip install keras-metrics